name: Build, tag and release Python wheel

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

permissions:
  contents: write

jobs:
  build-tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build toml

      - name: Build package
        run: |
          python -m build

      - name: Extract version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract project name
        run: |
          PROJECT_NAME=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['name'])")
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag v$VERSION
          git push origin v$VERSION

      - name: Release
        run: |
          gh release create v$VERSION \
            --title "Release v$VERSION"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload v$VERSION dist/$PROJECT_NAME-$VERSION-py3-none-any.whl
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}