name: Build and release Python wheel

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Set version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Build package
      run: |
        python -m build

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/custom_exceptions_lib-${{ env.VERSION }}-py3-none-any.whl
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        make_latest: true