name: Build and release Python wheel

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build toml

    - name: Build package
      run: |
        python -m build

    - name: Extract version
      run: |
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/custom_exceptions_lib-$VERSION-py3-none-any.whl
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        make_latest: true