name: Build and release Python wheel

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build
        ln -s custom_exceptions_lib-${{ steps.get_version.outputs.VERSION }}-py3-none-any.whl dist/custom_exceptions_lib.whl

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/custom_exceptions_lib.whl
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}